name: AntiCheatPlugin
version: 1.3.1
main: myplugin.AntiCheatPlugin
author: LibotorPro
api-version: 1.20

commands:
  timeout:
    permission: anticheat.timeout
  untimeout:
    permission: anticheat.untimeout

permissions:
  anticheat.timeout:
    default: op
  anticheat.untimeout:
    default: op
  anticheat.alert:
    default: op
  anticheat.bypass:
    default: op


